name: CI

on:
  push:
    branches:
      - main
      - email-service-setup
  pull_request:
    branches:
      - main
      - email-service-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting (flake8)
        run: |
          flake8
      - name: Coverage report
        run: |
          coverage run -m pytest
          coverage report
      - name: DjangoMails pytests
        run: |
          pytest
